name = "Log"
license = "GPL-3.0"
licenselink = "https://github.com/jakeprice-dev/hugo-theme-log/blob/master/LICENSE"
description = "Hugo Personal Log Theme"
homepage = "https://github.com/jakeprice-dev/hugo-theme-log"
tags = ["knowledge-base", "digital-garden", "journal", "notes", "wiki", "log"]
min_version = 0.87

[author]
  name = "Jake Price"
  homepage = "https://jakeprice.dev"
